---
title: "2019-04-03-Jane"
author: "Jane"
date: "2019年4月9日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")

```

```{r}
x3 == y3
x3 != y3

```

! negation 反向操作
```{r}
x3==y3
!(x3 == y3)
```

```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$幣別
```

head 會顯示物件前六個元素值
```{r}
head(currency)  
```

```{r}
levels(currency)
```


資料一進來並沒有被當成factor class
更正為factor class
```{r}
class(currency)

```

```{r}
currency <- as.factor(currency)
class(currency)

```

```{r}
levels(currency)
```

length(): 數向量內的元素個數(向量長度)
```{r}
length(levels(currency))

```

```{r}
step1_extractLevelsVector <- levels(currency)
step1_extractLevelsVector

step2_countVectorLength <- length(step1_extractLevelsVector)
step2_countVectorLength
```

多少筆日圓資料
```{r}
head(currency)
levels(currency)

```

```{r}
currency2 <- c("日圓","美元","日圓")
currency2
```

```{r}
sum(currency2 == "日圓")
```

```{r}

head(currency)
sum(currency == "日圓JPY/USD")

```

#5.4

```{r}
x5 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x5 %in% greatTaipei
```

```{r}
!(x5 %in% greatTaipei)
```

```{r}
y5 <- c("女","男","女")
y5

y5 == "女"
!(y5 == "女")

```

> 圈圏是要圏出"Relational Operation"為真的元素在物件內的「位置」

& : 同時滿足兩個條件
```{r}
x5
y5
x5 %in% greatTaipei
y5 == "女"
(x5 %in% greatTaipei) & (y5=="女")
```

```{r}
y5
y5 == "女"
which(y5=="女")

which((x5 %in% greatTaipei) & (y5 == "女"))
```

 | :滿足其中一個條件
```{r}
x5
y5
x5 %in% greatTaipei
y5 == "女"
(x5 %in% greatTaipei) | (y5=="女")

which((x5 %in% greatTaipei) | (y5=="女"))
```

xor:只滿足其中一個條件(either or)
```{r}
x5 %in% greatTaipei
y5 == "女"
xor(x5 %in% greatTaipei, y5=="女")
```

```{r}
which(xor(x5 %in% greatTaipei, y5=="女"))
```


# 綜合練習

```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
```

請把date的class存成date class。
```{r}
head(date)
```

```{r}
library(lubridate)
date <- ymd(date)
```

```{r}
class(date)
```

1980-08-01之後的資料有多少筆。
```{r}
isafter19800801 <-
  date >= ymd("1980-08-01")

```

```{r}
head(as.integer(date))
as.integer(ymd("1980-08-01"))
head(date >= ymd("1980-08-01"))
```

```{r}
class(isafter19800801)
sum(isafter19800801)
```

幣別為“歐元USD/EUR”的資料有多少筆。
```{r}
head(currency == "歐元USD/EUR")

isEURO <- currency == "歐元USD/EUR"

sum(isEURO)
```

```{r}
currency <- as.factor(currency)
class(currency)

isEURO <- currency == "歐元USD/EUR"
sum(isEURO)
```

exchangeRate有多少筆NA。
```{r}
isExchangeRateNA <- is.na(exchangeRate)
sum(isExchangeRateNA)
```

排除NA後，幣別為“歐元USD/EUR”的資料有多少筆。
```{r}
isNotNA <- !(is.na(exchangeRate))
isEURO <- currency ==  "歐元USD/EUR"
```

```{r}
satisfyBOth <- isNotNA & isEURO
sum(isNotNA & isEURO)
sum(satisfyBOth)
```























