---
title: "2019-05-15-Jane"
author: "Jane"
date: "2019年5月15日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
Vector1[["名稱4"]]
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 

```

```{r}
colnames(StuDF2) <- c("col1","col2","col3")
colnames(StuDF2)
StuDF2
```

```{r}
colnames(StuDF2)[[2]] <- c("姓名")
colnames(StuDF2)
StuDF2
```

```{r}
colnames(StuDF2)[c(2,3)] <- c("姓名","成績")
colnames(StuDF2)
StuDF2
```

```{r}
rownames(StuDF2)[[1]] <- c("小明的成績")
rownames(StuDF2)
StuDF2
```

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
```

```{r}
b[[3]] <- "FALSE"
b[[5]] <- "7"
b
```

```{r}
b$元素3 <- TRUE
b
b[["元素3"]] <- FALSE
b
```

```{r}
names(b)
b[["新元素A"]] <- c(1,2,3)
b$新元素B <- c(T,F,T)
b
```

```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```

```{r}
library(lubridate)
exData3$期間 <- ymd(exData3$期間)
class(exData3)
```

```{r}
exData3$isAsiaCrisis <- exData3$期間 >= ymd("1997-06-01") & exData3$期間 <= ymd("1998-12-01")
class(exData3$isAsiaCrisis)
```

```{r}
time1 <- ymd("1997-06-01")
time1
time2 <- ymd("1998-12-01")
time2
isAsiaCrisis <- exData3[[1]] <= time2 & exData3[[1]] >= time1
class(isAsiaCrisis)
isAsiaCrisis
```

```{r}
logiAsiaCrisis <- exData3$isAsiaCrisis
exData3[logiAsiaCrisis, ]

exData3[exData3$isAsiaCrisis==T ,]
exData3[exData3$isAsiaCrisis ,]
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
transcriptDataFinal[transcriptDataFinal$學號 == "92aS67fee", ]
```

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
f <- function(x,y){
  sum <- x+y
  return(sum) 
}

f(1,2)
```

```{r}
supply_fun <- function(a,b,P){
  Qs <- a+b*P
  return(Qs)}

demand_fun <- function(c,d,P){
  Qd <- c-d*P
  return(Qd)
}

supply_fun(0,1,1)
demand_fun(5,1,1)
```













































