---
title: "2019-04-24-Jane"
author: "Jane"
date: "2019年4月24日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
vec1 <- c(1:6)
vec1
```

```{r}
mat1 <- matrix(c(1:6),2,3)
mat1
```

```{r}
class(mat1)
typeof(mat1)
```

```{r}
mat1
mat1[[2]]
mat1[[6]]
```

```{r}
mat2 <- matrix(c("a","b","c","d"),2,2)
mat2
class(mat2)
typeof(mat2)

mat2[[2]]
mat2[c(T,F,F,T)]

```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```

```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
class(StuDF)
typeof(StuDF)

class(StuList)
typeof(StuList)
```

```{r}
StuDF

StuDF[[2]][[3]]
```

```{r}
class(StuDF$姓名)
```

```{r}
StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
class(StuDF2$姓名)
```

```{r}
as.data.frame(StuList) -> stuDF3
stuDF3
```

```{r}
stuDF4 <- as.data.frame(StuList,stringsAsFactors = F)
stuDF4
```

tolower 轉小寫
toupper 轉大寫
```{r}
chosenLETTERS <- LETTERS[1:15]
chosenLETTERS
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
tolower(matObj1)
toupper(matObj1) 
```

```{r}
chosenletters <- letters[1:16]
matobj2 <- matrix(chosenletters,4,4)
matobj2
```

```{r}
matObj1

matObj1[[8]]
matObj1[3,2]
matObj1[c(1,4),c(2,3)]
matObj1[c(T,F,F,T,F),c(F,T,T)]
matObj1[c(T,F,F,T,F),c(2,3)]
```

```{R}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```

```{r}
class(classSurvey)
```

```{r}
classSurvey[c(4,5)]
classSurvey[c("性別","本學期學分數")]
classSurvey[,4:5]
classSurvey[,c(4,5)]
classSurvey[,c(F,F,F,T,T,F)]
classSurvey[c(1:60),c(4,5)]

``` 

```{r}
classSurvey[logical_index,]
```


















