---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")

```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")

```

```{r}
dialogue  <- c("助教說：'明天要發考卷。'",
                "大家說：'Oh my god.'")

cat(dialogue, sep="\n")

```

```{r}

aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)

```

```{r}

sum(aLogical)

```

```{r}

studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```

```{r}

class(studentMajors)

```

```{r}

studentMajors0 <- c("經濟系", "經濟系", "法律系")

```

```{r}

class(studentMajors0)

```

```{r}

typeof(studentMajors)
```

```{r}

typeof(studentMajors0)

```

```{r}

levels(studentMajors)

```

```{r}

birthplace <- factor( c("台北市", "台中市", "台南市", "台北市", "台中市"))

class(birthplace)
levels(birthplace)
typeof(birthplace)
as.integer(birthplace)

```


```{r}

library(lubridate)

```

```{r}

dtObject<-ymd_hms("1970-01-01 00:02:53") 

```

```{r}

dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)

dtObject
typeof(dtObject)
as.double(dtObject)
class(dtObject)

```




```{r}

Sys.timezone()

```

